### ISSUE TITLE
Certificate container image gets overridden by Dark Mode

### ISSUE THREAD

**Issue by willdelorm** [sithu-khant/ztm-extension#12]
When Dark Mode is enabled, the course certificate container background gets overridden with the dark background. Could the certificate remain unaffected in Dark Mode?

Example certificate page:
![certificate-without-dark-mode](https://github.com/sithu-khant/ztm-extension/assets/91397515/d9db2fba-0447-4caa-87e8-1671856b4113)

Example certificate page with Dark Mode:
![certificate-with-dark-mode](https://github.com/sithu-khant/ztm-extension/assets/91397515/f82c046c-4cdd-40d4-9a2e-b846f663070e)

**Comment by sithu-khant** [comment]
Hello @willdelorm
It is just overwritten to UI. 
You will get the default certificate when you download it even if you are in the dark mode.
