### ISSUE TITLE
Is it possible to implement collapsible sections in the sidebar? 

### ISSUE THREAD

**Issue by RinoaHime** [sithu-khant/ztm-extension#34]
I'd like to be able to collapse/extend the different sections in the sidebar if possible. Thank you!

**Comment by sithu-khant** [comment]
In the video lecture learning page?

**Comment by RinoaHime** [comment]
Yes 
<img width="716" alt="image" src="https://github.com/sithu-khant/ztm-extension/assets/63169579/8553a251-af6d-439e-809c-c157df02fed0">

**Comment by RinoaHime** [comment]
By the way, love the time statistics on everything. I was looking for something like this
