### ISSUE TITLE
Instead of total time in the sections can we get time remaining instead?

### ISSUE THREAD

**Issue by RinoaHime** [sithu-khant/ztm-extension#35]
<img width="368" alt="image" src="https://github.com/sithu-khant/ztm-extension/assets/63169579/4a6524d2-ffec-400e-ada9-47b87a1a72e2">

**Comment by sithu-khant** [comment]
You can see the total watched time on the course info page, isn't?

<img width="812" alt="Screenshot 2024-04-26 at 6 37 40 AM" src="https://github.com/sithu-khant/ztm-extension/assets/122719409/9d09b0fa-7689-4dea-835f-ead59835e4bf">

**Comment by RinoaHime** [comment]
> You can see the total watched time on the course info page, isn't?
> 
> <img alt="Screenshot 2024-04-26 at 6 37 40 AM" width="812" src="https://private-user-images.githubusercontent.com/122719409/325806578-9d09b0fa-7689-4dea-835f-ead59835e4bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjc2MjgsIm5iZiI6MTcxNDI2NzMyOCwicGF0aCI6Ii8xMjI3MTk0MDkvMzI1ODA2NTc4LTlkMDliMGZhLTc2ODktNGRlYS04MzVmLWVhZDU5ODM1ZTRiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOFQwMTIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzA4NmQ4ZmI3NjBjZWM5ZDE1Mjc4ZjlmZjI0ZTdiYWUzNzgyY2EzYzVmM2ZkMmQ1ZDhiZDkyNjVhNTBiOGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gGVyWH8ZFbjPhOOxICaiNmQK6TsTUz_ZeuV4MGAzVHY">

Yes, but I'd prefer to see the total remaining time, though having the watched time is also nice
