### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by CruIIer** [sithu-khant/ztm-extension#37]
When running throught a course, after the lesson is completed the new lesson opens without full screen. Ok. I can always click "F" to put it on full screen - but it never works. When I'm in one lesson and the video is on full screen, I can exit the full screen with "F" and it works with the "F" from now on but with the new lesson I always have to click on the button - even clicking anywhere on the website what could activate the ability of "F" shortcut is not working - which is really annoying as some lessons have only a few minutes.

**Comment by sithu-khant** [comment]
You should first click the video area before clicking `F` to enter full screen after the new lecture shows up. That could work, i think. 

P.S. this is not about our extension. It is related to the learning platform, Teachable.
