### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by KevinBatdorf** [sithu-khant/ztm-extension#40]
What do you think about having something to sort by latest courses. Sometimes when there's a new course it's a pain to go look for it on the list. 

I can't tell from looking at the page source that there are url params to do this within teachable, but one possible option could be to add something a bit more complex (well, overengineered?)

1. Set up a GH Action to scrape https://academy.zerotomastery.io/courses/ (which is publically accessible) every day
2. Auto commit back to `main` with the course id, title, etc (everything in each card)
3. Rebuild the courses page dom entirely to rebuild the layout
4. Add sorting controls (leaving the current order as the default)
5. Optionally overtake the search bar too for instant searching

**Comment by aneagoie** [comment]
This is a really good idea... I never thought of using GH Action to do this, but that would really solve the "maintenance" issue we would encounter with constant course updates.

**Comment by sithu-khant** [comment]
I think you can easily search the course if you know the course name from the search bar.

+ I already tried "course sorting method" for the favorite course feature. It won't work. The reason is all the courses do not exist in one page, there is pagination. It is not possible to get all the course information though pagination via DOM. Because it is controlled by the back-end.

As you suggest, the courses from https://academy.zerotomastery.io/courses/ are only 32 courses, not all courses.

**Comment by KevinBatdorf** [comment]
@sithu-khant You'd have to remember the course name 😅😩🙈

But if scraping you'd also walk through the pagination too, of course (pun intended), so you can get a complete list. 

@aneagoie do you want a PR for this? Since the scraping is more useful in general I could do that first and follow up with something for the rendering, sorting, etc. But if you'd prefer to impliment it that's fine too.

**Comment by sithu-khant** [comment]
If you joined the academy server, you can look at in the announcement channel. Usually, people remember one keyboard from the course name. I mean even if I don't remember all the course name, I remember that course is about Python or JavaScript, sometimes even about automation bite course or network course.

Anyway, you are welcome to implement that feature if you want. But I can't confirm your PR will be merged. We have do decide that feature is well implemented or "necessary" or need to look at your code implementation.

**Comment by sithu-khant** [comment]
+ letting user to walk through the pagination to make the feature **working**, it is not a good product. As a truth, I don't like it. You should make the feature working by itself in the end. Should give the end-user the final product, not half-done one.

**Comment by KevinBatdorf** [comment]
Sorry if I wasn't clear, the scraper that runs in the GitHub action would be parsing the content and walking the pages, collecting the data, then auto commiting into main (or open a PR if preferred). The extension wouldn't be doing anything. 

Wait for the PR and I think it will make more sense.

**Comment by aneagoie** [comment]
@KevinBatdorf I like the idea. Would love a PR for this 🙏
