### ISSUE TITLE
Check workflow scheduler settings

### ISSUE THREAD

**Issue by KevinBatdorf** [sithu-khant/ztm-extension#45]
The workflow isn't running on the schedule. Can you double check the settings are correct?

https://github.com/sithu-khant/ztm-extension/settings/actions

It could be that because I made the last commit on the workflow file that it won't run on the schedule. If that's the case can you make an arbitrary commit with a new line or something. 

If you check my fork you see the same file is running every 24 hours: https://github.com/KevinBatdorf/ztm-extension/actions/workflows/scrape-courses.yml

I just did a manual run now which should open a PR with the latest update

**Comment by sithu-khant** [comment]
I am not sure about that, but I did all the settings you told.

**Comment by KevinBatdorf** [comment]
Ok cool thanks. Can check if it's working tomorrow.

GitHub gets weird with the scheduler. It could be I have the `git blame` for the scheduler line and idk maybe the access is too low. 

![image](https://github.com/user-attachments/assets/6e0c4ef4-f2ec-4677-bdca-483b9b85df53)

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule

You could just change the time by an hour or something to take over the `git blame` on that file. But can just run the workflow manually too though after a new course is released.
