### ISSUE TITLE
Dark mode on ZTM

### ISSUE THREAD

**Issue by HimansuWebCoder** [sithu-khant/ztm-extension#6]
It does not work  after add this extension

**Comment by sithu-khant** [comment]
what is the problem?

**Comment by noochxxo** [comment]
Today the option for dark mode disappeared. Sidebar toggle still works. But no longer is there an option for dark mode in the drop down menu with autocomplete and auto play. 
![Screen Shot 2023-12-22 at 9 32 56 PM](https://github.com/sithu-khant/ztm-extension/assets/18622872/59f59031-78d4-4626-80e3-ad800c6b8636)

**Comment by sithu-khant** [comment]
We updated our extension, the dark mode toggle bar will be in the popup.

<img width="341" alt="Screenshot 2023-12-23 at 10 09 44 AM" src="https://github.com/sithu-khant/ztm-extension/assets/122719409/088afa28-ff3b-4947-85ed-91d2749f2b13">
